<?php

const ERR_NO_MATCHING_REQUEST = 1;
const ERR_NO_MATCHING_REGISTRATION = 2;

const ERR_AUTHENTICATION_FAILURE = 3;
const ERR_UNMATCHED_CHALLENGE = 4;

const ERR_ATTESTATION_SIGNATURE = 5;

// ERR_ATTESTATION_VERIFICATION = 6  for tests;

const ERR_COUNTER_TOO_LOW = 8;
const ERR_PUBKEY_DECODE = 9;

// ERR_OLD_OPENSSL = 11  (OPENSSL_VERSION_NUMBER < 0x10000000);

const ERR_NO_MATCHING_ORIGIN = 12;
const ERR_BAD_TYPE = 13;
const ERR_BAD_USER_PRESENCE = 14;


